table company_expenses
	lineageTag: 2324e7d4-7475-4b60-b0d9-c3e2e28aaa3f

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: a68786fd-640e-486f-9d5f-3ce7c4336e81
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: cb7182d7-e129-4c77-b417-1474931e0ee6
			defaultHierarchy: LocalDateTable_5420ee6b-87aa-44b4-9aeb-3866642b4b92.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Expense Category'
		dataType: string
		lineageTag: ff05f1dd-2417-4b1b-8172-1057c0d1f9e4
		summarizeBy: none
		sourceColumn: Expense Category

		annotation SummarizationSetBy = Automatic

	column 'Expense Items'
		dataType: string
		lineageTag: b16f4f5d-9313-4c42-88d8-10222854a627
		summarizeBy: none
		sourceColumn: Expense Items

		annotation SummarizationSetBy = Automatic

	column 'Expense Values'
		dataType: double
		lineageTag: 643c09ae-5ceb-4890-bd02-0edb64922a39
		summarizeBy: sum
		sourceColumn: Expense Values

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition company_expenses = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ADMIN\OneDrive - Deakin University\Documents\Development\Databricks_CafeShop_Project\data_raw\data\financial\company_expenses.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Month", type date}, {"Expense Category", type text}, {"Expense Items", type text}, {"Expense Values", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

