table 'Income Statement Analysis'
	lineageTag: 7ceb1cc1-30d0-427d-8307-2774b35836dd

	measure 'Income Values' = SUM('Income Statement Data'[Expense Values])
		lineageTag: aa1663a6-c55c-4dde-9122-1f86b78ef7c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actuals (,000)' = ```
			
			VAR Revenue = CALCULATE([Income Values], 'Income Statement Data'[Type] = "Revenues")
			VAR Expense = CALCULATE([Income Values], 'Income Statement Data'[Type] = "Expenses")*-1
			
			RETURN 
			DIVIDE(
			    IF( SELECTEDVALUE('Income Statement Data'[Type]) = "Revenues", Revenue, 
			        IF( SELECTEDVALUE('Income Statement Data'[Type]) = "Expense", Expense,
			         Revenue + Expense)),1000,0)
			```
		lineageTag: 71b4ff74-4742-4641-883f-e434eb672875

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure COGS = ```
			
			 CALCULATE( [Income Values], 'Income Statement Data'[Expense Category] = "Cost Of Goods Sold" )*(-1)
			```
		lineageTag: b7350f97-f5ac-47ef-bf14-e2b669ca4059

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Revenues =
			
			CALCULATE('Income Statement Analysis'[Income Values], 'Income Statement Data'[Type]="Revenues")
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8e226f9f-d46a-4f95-aaeb-c0d45a839ac2

	measure 'Gross Profit' =
			
			[Revenues] - [COGS]
		lineageTag: 5bda2497-4161-4c61-9fff-402db369a1ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit Margin' =
			
			DIVIDE([Gross Profit], [Revenues],0)
		lineageTag: 29c2b0ba-1da1-4288-b66c-4a71e14f941a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Other Expenses' =
			
			(CALCULATE([Income Values], 'Income Statement Data'[Type]="Expenses") + [COGS]) * -1 -- Supposed to subtract COGS since Expences includes COGS but in the formula, COGS is alreay in minus
		lineageTag: bc74419f-6b20-4c23-b73e-9044e102a278

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Profit' = [Revenues] + [COGS] + [Other Expenses] -- Should be subtracting [COGS] and [Other Expenses] but they already in minus in their formula so we don't have to subtract in this one
		lineageTag: bc5b3616-2639-4fdf-9e63-4b4370cd62c6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Profit Margin' =
			
			DIVIDE([Net Profit], [Revenues],0)
		lineageTag: be9a19f3-bf1c-44b4-9a9c-6ed8b81267eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Year Actuals' =
			
			VAR CurrentItem = SELECTEDVALUE( 'Template Income Statement'[Items (Normalized)] )
			RETURN
			    SWITCH( TRUE(),
			    CurrentItem = "Total Revenues", DIVIDE( [Revenues], 1000, 0),
			    CurrentItem = "Total COGS" , DIVIDE( [COGS], 1000, 0),
			    CurrentItem = "Total Gross Profit", DIVIDE( [Gross Profit], 1000, 0),
			    CurrentItem = "Gross Profit %", FORMAT( [Gross Profit Margin], "0.00%"),
			    CurrentItem = "Total Other Expenses", DIVIDE( [Other Expenses], 1000, 0),
			    CurrentItem = "Total Net Profit", DIVIDE( [Net Profit], 1000, 0),
			    CurrentItem = "Net Profit %", FORMAT( [Net Profit Margin], "0.00%"),
			    CALCULATE([Actuals (,000)], FILTER('Income Statement Data', 'Income Statement Data'[Expense Items] =  CurrentItem)))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: eb183936-998e-4a38-a915-dd700965e784

	measure 'Revenues LY' =
			
			CALCULATE([Revenues], DATEADD(dim_date[Date], -1, YEAR))
		displayFolder: Last Year
		lineageTag: 312d5d5d-4cf7-4909-876c-cc62ece653fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'COGS LY' =
			
			CALCULATE([COGS], DATEADD(dim_date[Date], -1, YEAR))
		displayFolder: Last Year
		lineageTag: 79fa1923-445a-4fd1-93d1-c7868b63076d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Other Expenses LY' =
			
			CALCULATE([Other Expenses], DATEADD(dim_date[Date], -1, YEAR))
		displayFolder: Last Year
		lineageTag: 8bba38d3-14ea-42e2-bc2d-4dd5503d3aea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Gross Profit LY' =
			
			CALCULATE([Gross Profit], DATEADD(dim_date[Date], -1, YEAR))
		displayFolder: Last Year
		lineageTag: e4684e2b-dfa9-4b1e-8022-07045b1658d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Profit LY' =
			
			CALCULATE([Net Profit], DATEADD(dim_date[Date], -1, YEAR))
		displayFolder: Last Year
		lineageTag: 6f9de65a-3ea4-4a24-b95b-10d1acbc432d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Profit Margin LY' =
			
			CALCULATE([Net Profit Margin], DATEADD(dim_date[Date], -1, YEAR))
		displayFolder: Last Year
		lineageTag: a2792634-487a-4dd4-bedd-295c2d4e9828

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Previous Year Actuals' =
			
			VAR CurrentItem = SELECTEDVALUE( 'Template Income Statement'[Items (Normalized)] )
			RETURN
			    SWITCH( TRUE(),
			    CurrentItem = "Total Revenues", DIVIDE( [Revenues LY], 1000, 0),
			    CurrentItem = "Total COGS" , DIVIDE( [COGS LY], 1000, 0),
			    CurrentItem = "Total Gross Profit", DIVIDE( [Gross Profit LY], 1000, 0),
			    CurrentItem = "Total Other Expenses", DIVIDE( [Other Expenses LY], 1000, 0),
			    CurrentItem = "Total Net Profit", DIVIDE( [Net Profit LY], 1000, 0),
			    CurrentItem = "Gross Profit %", FORMAT( [Gross Profit Margin LY], "0.00%"),
			    CurrentItem = "Net Profit %", FORMAT( [Net Profit Margin LY], "0.00%"),
			    CALCULATE([Actuals (,000)], FILTER('Income Statement Data', 'Income Statement Data'[Expense Items] =  CurrentItem), DATEADD(dim_date[Date], -1, YEAR))
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Last Year
		lineageTag: dd816f66-9541-4b56-87ea-e32558c995f4

	measure 'Gross Profit Margin LY' =
			
			CALCULATE([Gross Profit Margin], DATEADD(dim_date[Date], -1, YEAR))
		displayFolder: Last Year
		lineageTag: 98af5ed0-5b3a-45c5-a4e4-4287d01b936b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'TY vs LY Actuals' = ```
			
			VAR CurrentItem = SELECTEDVALUE( 'Template Income Statement'[Items (Normalized)] )
			RETURN
			    SWITCH( TRUE(),
			    CurrentItem = "Total Revenues", DIVIDE([Revenues] - [Revenues LY], 1000, 0),
			    CurrentItem = "Total COGS" , DIVIDE([COGS] - [COGS LY], 1000, 0),
			    CurrentItem = "Total Gross Profit", DIVIDE( [Gross Profit] - [Gross Profit LY], 1000, 0),
			    CurrentItem = "Total Other Expenses", DIVIDE( [Other Expenses] - [Other Expenses LY], 1000, 0),
			    CurrentItem = "Total Net Profit", DIVIDE([Net Profit] - [Net Profit LY], 1000, 0),
			    CurrentItem = "Gross Profit %", FORMAT( [Gross Profit Margin] - [Gross Profit Margin LY], "0.00%"),
			    CurrentItem = "Net Profit %", FORMAT( [Net Profit Margin] - [Net Profit Margin LY], "0.00%"),
			    CALCULATE([Actuals (,000)], FILTER('Income Statement Data', 'Income Statement Data'[Expense Items] =  CurrentItem)) - 
			        CALCULATE(
			            CALCULATE([Actuals (,000)], FILTER('Income Statement Data', 'Income Statement Data'[Expense Items] =  CurrentItem)), 
			            DATEADD(dim_date[Date], -1, YEAR))
			    
			)
			```
		displayFolder: Last Year
		lineageTag: 0318ed63-251b-4631-88ec-7120afba523c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'DEBUG_Test Date Range' =
			
			CONCATENATE(
			    FORMAT(MIN(dim_date[Date]), "MMM YYYY"),
			    " to " & FORMAT(MAX(dim_date[Date]), "MMM YYYY")
			)
		lineageTag: 173ff490-06ad-45bb-b0f1-ea2579622ca9

	measure 'TY vs LY Actuals %' = ```
			
			VAR CurrentItem = SELECTEDVALUE( 'Template Income Statement'[Items (Normalized)] )
			RETURN
			    SWITCH( TRUE(),
			    CurrentItem = "Total Revenues", DIVIDE([Revenues],[Revenues LY], 0),
			    CurrentItem = "Total COGS" , DIVIDE([COGS],[COGS LY], 0),
			    CurrentItem = "Total Gross Profit", DIVIDE( [Gross Profit],[Gross Profit LY], 0),
			    CurrentItem = "Total Other Expenses", DIVIDE( [Other Expenses],[Other Expenses LY], 0),
			    CurrentItem = "Total Net Profit", DIVIDE([Net Profit], [Net Profit LY], 0),
			    CurrentItem = "Gross Profit %", FORMAT( [Gross Profit Margin] - [Gross Profit Margin LY], "0.00%"),
			    CurrentItem = "Net Profit %", FORMAT( [Net Profit Margin] - [Net Profit Margin LY], "0.00%"),
			    DIVIDE([TY vs LY Actuals],
			        ABS(CALCULATE(CALCULATE( [Actuals (,000)],
			        FILTER('Income Statement Data', 'Income Statement Data'[Expense Items] = CurrentItem)), 
			        DATEADD(dim_date[Date], -1, YEAR)))
			))
			```
		displayFolder: Last Year
		lineageTag: 3294b2ef-2097-41ad-92f3-b9c16da4ebc9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Income Statement Analysis' = m
		mode: import
		queryGroup: 'Measures Group'
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

