table 'Income Statement Analysis'
	lineageTag: 7ceb1cc1-30d0-427d-8307-2774b35836dd

	measure 'Income Values' = SUM('Income Statement Data'[Expense Values])
		lineageTag: aa1663a6-c55c-4dde-9122-1f86b78ef7c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actuals (,000)' = ```
			
			VAR Revenue = CALCULATE([Income Values], 'Income Statement Data'[Type] = "Revenues")
			VAR Expense = CALCULATE([Income Values], 'Income Statement Data'[Type] = "Expenses")*-1
			
			RETURN 
			DIVIDE(
			    IF( SELECTEDVALUE('Income Statement Data'[Type]) = "Revenues", Revenue, 
			        IF( SELECTEDVALUE('Income Statement Data'[Type]) = "Expense", Expense,
			         Revenue + Expense)),1000,0)
			```
		lineageTag: 71b4ff74-4742-4641-883f-e434eb672875

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Income Statement Analysis' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

