table 'Income Statement Data'
	lineageTag: ccae6a89-c50e-40ae-85a6-7f53bd277f02

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: a3f22bd9-8a81-4c89-b5b7-a544c3639154
		summarizeBy: none
		sourceColumn: Month

		variation Variation
			isDefault
			relationship: 44de591e-1fe3-47b3-ba35-a1f1920e2c5c
			defaultHierarchy: LocalDateTable_c0f869c8-201c-493a-bd9e-f2940cbca605.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Expense Category'
		dataType: string
		lineageTag: ce28767c-27e8-441c-802c-66f883dc1f4a
		summarizeBy: none
		sourceColumn: Expense Category

		annotation SummarizationSetBy = Automatic

	column 'Expense Items'
		dataType: string
		lineageTag: 92685e45-3a18-44f0-8ce5-3521c1836d16
		summarizeBy: none
		sourceColumn: Expense Items

		annotation SummarizationSetBy = Automatic

	column 'Expense Values'
		dataType: double
		lineageTag: f82f6066-2af6-475e-ad76-b83e78626dce
		summarizeBy: sum
		sourceColumn: Expense Values

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Type =
			
			IF('Income Statement Data'[Expense Category] = "Revenue", "Revenues","Expenses")
		lineageTag: 9e6d71c6-ec14-484d-9907-7a8d82a9fa62
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Type Index' =
			
			IF('Income Statement Data'[Expense Category] = "Revenue", 1,2)
		formatString: 0
		lineageTag: 19816cc3-6467-4983-a8ff-879d26518aaf
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Income Statement Data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Nobit\Documents\Databricks_CafeShop_Project\data_raw\data\financial\income_statement_data.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Month", type date}, {"Expense Category", type text}, {"Expense Items", type text}, {"Expense Values", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

