table Table_Weeks_Back
	lineageTag: 9a3b7892-b87e-4b70-931d-61eb36f4fc31

	column Key
		dataType: string
		lineageTag: 42991179-f84f-419d-b1d5-e9e2ff3137a0
		summarizeBy: none
		sourceColumn: Key

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: 28bb6f45-f33d-4b2b-86a3-b41c35c4d847
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition Table_Weeks_Back = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlQoT03NVtJRMlSK1YlWMgJyE7OLgXwjMN8ELA3im4D5FnC+hVJsLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Key"}, {"Column2", "Value"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

